directory. A report template named inventory.csv.j2 is given under the templates directory.

Update the template to print the requested details of all hosts defined in /home/bob/playbooks/inventory/inventory file. Further update /home/bob/playbooks/inventory/generate-inventory.yml playbook to generate the report and place it on the student-node node at /tmp/inventory.csv.


Use below variables from the gathered facts for each host.

hostname, architecture, distribution_version, mem_total_mb, processor_cor$
hostname, architecture, distribution_version, mem_total_mb, processor_cor$
{% for host in groups['web'] %}
{{ host }}, {{ hostvars[host]['ansible_architecture'] }}, {{ hostvars[hos$
{% endfor %}

# generate-inventory.yml

- hosts: all
  tasks:
  - setup:

- hosts: localhost
  tasks:
    - template:
        src: inventory.csv.j2
        dest: /tmp/inventory.csv
      run_once: yes
